groups:
  - name: ffhl
    rules:
    - record: "fastd_peer_traffic_sum"
      expr: 'sum by (key, name) (rate(fastd_peer_traffic{iface=~"ffhl_mesh_vpn.*", kind="bytes", type=~"rx|tx"}[1m]))'
    - record: "mesh_links"
      expr: 'count by (link_type, community) (link_tq{link_type!="undefined"})'

    - record: "nodes_online_percentage"
      expr: 'meshnodes_online_total{job="hopglass"} / meshnodes_total{job="hopglass"}'

    - record: "mesh_avg_link_quality"
      expr: 'avg by (link_type, community)(link_tq{link_type!="undefined"})'

    - record: "mesh_connected_clients_24"
      expr: 'avg_over_time(total_clients{job="hopglass"}[24h])'

    - record: "firmware_distribution"
      expr: 'count by (firmware, community)(online{firmware!="", instance_!="hopglass"})'

    - record: "device_distribution"
      expr: 'count by (model, community)(online{model!="", instance_!="hopglass"})'

    - record: "gateway_distribution"
      expr: 'count by (gateway, community) (online{gateway!="", job="hopglass"})'

    - record: "mesh_sum_traffic_type"
      expr: 'sum by (type, community) (rate(statistics_traffic[300s]))'

    - record: "mesh_sum_traffic_mtype"
      expr: 'sum by (mtype, community) (rate(statistics_traffic[300s]))'

    - record: "node_statistics_traffic"
      expr: 'sum by (nodeid, mtype, community) (rate(statistics_traffic{site="ffhl", instance_!="hopglass"}[5m]) * 8)'
