---

#
# install prometheus
#
- name: install prometheus
  apt:
    update_cache: yes
    state: latest
    name: prometheus

- name: copy prometheus config files
  notify: restart prometheus
  copy:
    src: "prometheus/{{ item }}"
    dest: /etc/prometheus/
  loop:
    - "first_rules.yml"
    - "prometheus.yml"

- name: copy defaults config
  notify: restart prometheus
  copy:
    src: prometheus-default
    dest: /etc/default/prometheus

- name: enable prometheus
  systemd:
    enabled: yes
    name: prometheus


#
# Install Grafana
#

- name: add grafana repo pubkey
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: setup grafana repo
  copy:
    src: grafana.list
    dest: /etc/apt/sources.list.d/

- name: install grafana
  apt:
    update_cache: yes
    state: latest
    name: grafana

- name: copy defaults config
  notify: restart grafana
  template:
    src: grafana.ini
    dest: /etc/grafana/
